CREATE TABLE employees
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    department   VARCHAR(255)                            NOT NULL,
    role         VARCHAR(255)                            NOT NULL,
    joining_date DATE                                    NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE review_cycles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    start_date DATE                                    NOT NULL,
    end_date   DATE                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_review_cycles PRIMARY KEY (id),
    CONSTRAINT uk_review_cycles_name UNIQUE (name)
);

CREATE TABLE goals
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id     BIGINT                                  NOT NULL,
    review_cycle_id BIGINT                                  NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_goals PRIMARY KEY (id)
);

CREATE TABLE performance_reviews
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id     BIGINT                                  NOT NULL,
    review_cycle_id BIGINT                                  NOT NULL,
    reviewer_id     BIGINT                                  NOT NULL,
    rating          SMALLINT                                NOT NULL,
    notes           TEXT,
    submitted_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_performance_reviews PRIMARY KEY (id),
    CONSTRAINT uq_review_per_reviewer_cycle UNIQUE (employee_id, review_cycle_id, reviewer_id)
);

ALTER TABLE goals
    ADD CONSTRAINT fk_goals_on_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE goals
    ADD CONSTRAINT fk_goals_on_review_cycle FOREIGN KEY (review_cycle_id) REFERENCES review_cycles (id);

ALTER TABLE performance_reviews
    ADD CONSTRAINT fk_performance_reviews_on_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE performance_reviews
    ADD CONSTRAINT fk_performance_reviews_on_review_cycle FOREIGN KEY (review_cycle_id) REFERENCES review_cycles (id);

ALTER TABLE performance_reviews
    ADD CONSTRAINT fk_performance_reviews_on_reviewer FOREIGN KEY (reviewer_id) REFERENCES employees (id);
